package com.boardgamefiesta.powergrid.logic;

public enum PowerGridError {
    NOT_ENOUGH_AVAILABLE, NOT_AUCTION_PHASE, AUCTION_IN_PROGRESS, BALANCE_TOO_LOW, MUST_START_AUCTION, NO_AUCTION_IN_PROGRESS, BID_TOO_LOW, NOT_BUREAUCRACY_PHASE, ALREADY_PRODUCED_THIS_ROUND, NOT_ENOUGH_PLAYERS, TOO_MANY_PLAYERS, INVALID_NUMBER_OF_AREAS, INVALID_ACTION, NOT_BIDDING_PLAYER, NOT_PLAYERS_TURN, POWER_PLANT_NOT_AVAILABLE
}
