AWSTemplateFormatVersion: "2010-09-09"
Description: VPC for Board Game Fiesta
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-private-a'
      VpcId: !Ref VPC

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-private-b'
      VpcId: !Ref VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn:
      - InternetGateway
      - VPCGatewayAttachment
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-a'
      VpcId: !Ref VPC

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    DependsOn:
      - InternetGateway
      - VPCGatewayAttachment
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-b'
      VpcId: !Ref VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public'
      VpcId: !Ref VPC

  PublicSubnetARouteTableAttachment:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetA

  PublicSubnetBRouteTableAttachment:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetB

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-private'
      VpcId: !Ref VPC

  PrivateSubnetARouteTableAttachment:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnetA

  PrivateSubnetBRouteTableAttachment:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnetB

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}:VPC'
  PublicSubnetA:
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub '${AWS::StackName}:PublicSubnetA'
  PublicSubnetB:
    Value: !Ref PublicSubnetB
    Export:
      Name: !Sub '${AWS::StackName}:PublicSubnetB'
  PrivateSubnetA:
    Value: !Ref PrivateSubnetA
    Export:
      Name: !Sub '${AWS::StackName}:PrivateSubnetA'
  PrivateSubnetB:
    Value: !Ref PrivateSubnetB
    Export:
      Name: !Sub '${AWS::StackName}:PrivateSubnetB'
