@startuml

actor User

database Database <<AWS DynamoDB>>

frame Backend {
  component [REST API Gateway] <<AWS API Gateway>>
  component [REST API] <<AWS Lambda>>
  [REST API Gateway] --> [REST API]

  component [WebSocket API Gateway] <<AWS API Gateway>>
  component [WebSocket API] <<AWS Lambda>>
  [WebSocket API Gateway] --> [WebSocket API]

  component [Automa Executor] <<AWS Lambda>>
  () Queue <<AWS SQS>>
  [Automa Executor] - Queue
  [Automa Executor] --> Queue

  [REST API] --> Queue

  component [Cognito Trigger] <<AWS Lambda>>

  [REST API] --> Database
  [WebSocket API] --> Database
  [Automa Executor] --> Database
}

component [Identity Provider] <<AWS Cognito>>
[Identity Provider] --> [Cognito Trigger]
[REST API] --> [Identity Provider]
[WebSocket API] --> [Identity Provider]

User --> [REST API Gateway]
User --> [WebSocket API Gateway]
User --> [Identity Provider]

@enduml