@startuml
actor User
frame BoardGameFiesta {
    component WebApp
    component Backend
    component IdentityProvider
    database Database
    WebApp --> Backend
    Backend --> Database
    Backend --> IdentityProvider
}
User --> WebApp
User --> IdentityProvider
Backend --> [PaymentProvider]
Backend --> [EmailServer]
@enduml