/*
 * Board Game Fiesta
 * Copyright (C)  2022 Tom Wetjens <tomwetjens@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.boardgamefiesta.dominantspecies.logic;

public enum DominantSpeciesError {
    ACTION_SPACE_EMPTY,
    ACTION_SPACE_NOT_ALLOWED,
    ACTION_SPACE_NOT_EMPTY,
    ALREADY_ELEMENT_AT_CORNER,
    ALREADY_TILE_AT_HEX,
    ALREADY_TUNDRA,
    ANIMAL_NOT_FOUND,
    CANNOT_MOVE_THROUGH_BLANK_HEX,
    CANNOT_PERFORM_ACTION,
    CANNOT_REMOVE_ELEMENT,
    CANNOT_SKIP_ACTION,
    CANNOT_SKIP_MORE_ELEMENT_TYPES_THAN_ACTION_PAWNS_PLACED,
    CARD_NOT_AVAILABLE,
    DUPLICATE_TILES,
    DUPLICATE_TILE_TYPES,
    ELEMENT_NOT_AVAILABLE,
    ELEMENT_NOT_FOUND,
    ELEMENT_NOT_IN_DEPLETION_BOX,
    ELEMENT_NOT_IN_DRAW_BAG,
    ELEMENT_NOT_IN_REGRESSION_BOX,
    INVALID_ACTION_SPACE,
    INVALID_ELEMENT_TYPE,
    INVALID_HEX,
    INVALID_MOVE,
    INVALID_SPECIES,
    INVALID_TILE,
    MAX_4_SPECIES_ALLOWED,
    MAX_5_ELIMINATED_SPECIES_ALLOWED,
    MAX_DISTANCE_EXCEEDED,
    MAX_ELEMENTS_REACHED,
    MAX_SPECIES_EXCEEDED,
    MUST_BE_ADJACENT_TO_AQUATIC_TILE,
    MUST_BE_ADJACENT_TO_ELEMENT,
    MUST_BE_ADJACENT_TO_TILE,
    MUST_BE_ADJACENT_TO_TUNDRA_TILE,
    MUST_BE_MAMMALS,
    MUST_MOVE_ALL_SPECIES_ON_TILE,
    MUST_SELECT_1_TILE,
    MUST_SELECT_ADJACENT_TILES,
    MUST_SELECT_ALL_ADJACENT_TILES,
    MUST_SELECT_ALL_AFFECTED_TILES,
    MUST_SELECT_ALL_BUT_1_ELEMENT_ON_TILE,
    MUST_SELECT_ALL_TILES_OCCUPIED_BY_PLAYER,
    MUST_SELECT_ANIMAL_FOR_EACH_TILE,
    MUST_SELECT_AT_LEAST_1_TILE,
    MUST_SELECT_DIFFERENT_PLAYERS,
    MUST_SELECT_OPPOSING_SPECIES,
    MUST_SELECT_UP_TO_2_TILES,
    MUST_SELECT_UP_TO_3_TILES,
    MUST_SPECIFY_SPECIES_FOR_EACH_TILE,
    NOT_CURRENT_PLAYER,
    NOT_ENOUGH_ELIMINATED_SPECIES,
    NOT_ENOUGH_SPECIES_IN_GENE_POOL,
    NOT_ENOUGH_SPECIES_ON_TILE,
    NOT_OPPOSING_SPECIES,
    NO_ACTION_PAWN,
    NO_ACTION_TO_SKIP,
    NO_ELEMENTS_IN_DRAW_BAG,
    NO_ELEMENT_AT_CORNER,
    NO_TILE_AVAILABLE,
    NO_TILE_SCORED,
    NO_TILE_SELECTED,
    NO_TUNDRA_TILE_AVAILABLE,
    SPECIES_MUST_BE_POSITIVE,
    TILE_ALREADY_SCORED,
    TILE_NOT_FOUND,
    MAX_6_PLAYERS, MIN_1_PLAYER, INVALID_PLAYER, TILE_NOT_OCCUPIED_BY_PLAYER
}
