package com.boardgamefiesta.istanbul.logic;

public enum IstanbulError {
    CANNOT_PERFORM_ACTION,
    CANNOT_SKIP_ACTION,
    NO_ACTION,
    NOT_ENOUGH_GOODS,
    ALREADY_HAS_MOSQUE_TILE,
    MOSQUE_TILE_NOT_AVAILABLE,
    PLACE_NOT_REACHABLE,
    NOT_AT_PLACE,
    NO_ASSISTANTS_AVAILABLE,
    NOT_ENOUGH_LIRA,
    INVALID_GUESS,
    NO_RUBY_AVAILABLE,
    NO_FAMILY_MEMBER_TO_CATCH,
    NO_BONUS_CARD_AVAILABLE,
    DOESNT_HAVE_BONUS_CARD,
    CANNOT_ADD_EXTENSION,
    ALREADY_AT_PLACE
}
