package com.tomsboardgames.server.domain;

public enum APIError {
    NO_SUCH_USER,
    EXCEEDS_MAX_REALTIME_GAMES,
    CANNOT_INVITE_YOURSELF,
    GAME_ALREADY_STARTED_OR_ENDED,
    GAME_NOT_STARTED,
    NOT_INVITED,
    ALREADY_RESPONDED,
    MUST_BE_OWNER,
    NOT_PLAYER_IN_GAME,
    NOT_YOUR_TURN,
    MUST_SPECIFY_USERNAME_OR_EMAIL,
    MIN_PLAYERS,
    EXCEEDS_MAX_PLAYERS,
    GAME_ALREADY_ENDED, ALREADY_LEFT, ALREADY_PROPOSED_TO_LEAVE, NOT_ACCEPTED, CANNOT_ABANDON, GAME_ABANDONED, ALREADY_INVITED, NOT_SUPPORTED, NO_SUCH_ACTION
}
