package com.tomsboardgames.istanbul.logic;

public enum IstanbulError {
    CANNOT_PERFORM_ACTION,
    CANNOT_SKIP_ACTION,
    NO_ACTION,
    NOT_ENOUGH_GOODS,
    ALREADY_HAS_MOSQUE_TILE,
    MOSQUE_TILE_NOT_AVAILABLE,
    TOO_MANY_STEPS,
    NOT_AT_PLACE,
    NO_ASSISTANTS_AVAILABLE,
    NOT_ENOUGH_LIRA,
    INVALID_GUESS,
    MUST_SPECIFY_GOODS_TYPE,
    NO_RUBY_AVAILABLE,
    NO_OTHER_FAMILY_MEMBER_AT_PLACE,
    BONUS_CARD_NOT_AVAILABLE,
    ALREADY_AT_PLACE
}
