package com.wetjens.gwt;

public enum StationMaster {

    GAIN_2_DOLLARS_POINT_FOR_EACH_WORKER,
    REMOVE_HAZARD_TEEPEE_POINTS_FOR_EACH_2_OBJECTIVE_CARDS,
    PERM_CERT_POINTS_FOR_EACH_2_HAZARDS,
    PERM_CERT_POINTS_FOR_TEEPEE_PAIRS,
    PERM_CERT_POINTS_FOR_EACH_2_CERTS;

}
